- ros_topic_name: <robot_namespace>/joint_states
  gz_topic_name: <robot_namespace>/joint_states
  ros_type_name: sensor_msgs/msg/JointState
  gz_type_name: gz.msgs.Model
  direction: GZ_TO_ROS
- ros_topic_name: <robot_namespace>/odom
  gz_topic_name: <robot_namespace>/odom
  ros_type_name: nav_msgs/msg/Odometry
  gz_type_name: gz.msgs.Odometry
  direction: GZ_TO_ROS
- ros_topic_name: <robot_namespace>/odom_gt
  gz_topic_name: <robot_namespace>/odom_gt
  ros_type_name: nav_msgs/msg/Odometry
  gz_type_name: gz.msgs.Odometry
  direction: GZ_TO_ROS
- ros_topic_name: <robot_namespace>/cmd_vel
  gz_topic_name: <robot_namespace>/cmd_vel
  ros_type_name: geometry_msgs/msg/TwistStamped
  gz_type_name: gz.msgs.Twist
  direction: ROS_TO_GZ
- ros_topic_name: <robot_namespace>/imu
  gz_topic_name: <robot_namespace>/imu
  ros_type_name: sensor_msgs/msg/Imu
  gz_type_name: gz.msgs.IMU
  direction: GZ_TO_ROS
  qos_profile: SENSOR_DATA
- ros_topic_name: <robot_namespace>/microstrain/imu/data
  gz_topic_name: <robot_namespace>/microstrain/imu/data
  ros_type_name: sensor_msgs/msg/Imu
  gz_type_name: gz.msgs.IMU
  direction: GZ_TO_ROS
  qos_profile: SENSOR_DATA
- ros_topic_name: <robot_namespace>/microstrain/imu/mag
  gz_topic_name: <robot_namespace>/microstrain/imu/mag
  ros_type_name: sensor_msgs/msg/MagneticField
  gz_type_name: gz.msgs.Magnetometer
  direction: GZ_TO_ROS
  qos_profile: SENSOR_DATA
- ros_topic_name: <robot_namespace>/lidar_points_raw
  gz_topic_name: <robot_namespace>/lidar_points/points
  ros_type_name: sensor_msgs/msg/PointCloud2
  gz_type_name: gz.msgs.PointCloudPacked
  direction: GZ_TO_ROS
  qos_profile: SENSOR_DATA
- ros_topic_name: <robot_namespace>/front_camera/image
  gz_topic_name: <robot_namespace>/front_camera/image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
  qos_profile: SENSOR_DATA
- ros_topic_name: <robot_namespace>/front_camera/camera_info
  gz_topic_name: <robot_namespace>/front_camera/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
  qos_profile: SENSOR_DATA
- ros_topic_name: <robot_namespace>/navsat
  gz_topic_name: <robot_namespace>/navsat
  ros_type_name: sensor_msgs/msg/NavSatFix
  gz_type_name: gz.msgs.NavSat
  direction: GZ_TO_ROS
  qos_profile: SENSOR_DATA
