/**:
  ros__parameters:
    port: <foxglove_port>
    address: <foxglove_address>
    num_threads: 2
    send_buffer_limit: 1000000
    max_qos_depth: 5
    topic_whitelist:
    - ^/clock$
    - ^/rosout$
    - ^/<robot_namespace>/battery_state$
    - ^/<robot_namespace>/clicked_point$
    - ^/<robot_namespace>/cmd_vel$
    - ^/<robot_namespace>/cmd_vel_auto$
    - ^/<robot_namespace>/cmd_vel_joy$
    - ^/<robot_namespace>/cmd_vel_nav$
    - ^/<robot_namespace>/cmd_vel_smoothed$
    - ^/<robot_namespace>/cmd_vel_teleop$
    - ^/<robot_namespace>/estop$
    - ^/<robot_namespace>/estop_lock$
    - ^/<robot_namespace>/fixposition/datum$
    - ^/<robot_namespace>/fixposition/odometry_enu$
    - ^/<robot_namespace>/fixposition/odometry_llh$
    - ^/<robot_namespace>/fixposition/odometry_smooth$
    - ^/<robot_namespace>/fixposition/speed$
    - ^/<robot_namespace>/front_camera/camera_info$
    - ^/<robot_namespace>/front_camera/image$
    - ^/<robot_namespace>/global_costmap/costmap$
    - ^/<robot_namespace>/goal_pose$
    - ^/<robot_namespace>/ground_points$
    - ^/<robot_namespace>/imu$
    - ^/<robot_namespace>/initialpose$
    - ^/<robot_namespace>/joint_states$
    - ^/<robot_namespace>/joy$
    - ^/<robot_namespace>/lidar_imu$
    - ^/<robot_namespace>/lidar_points_filtered$
    - ^/<robot_namespace>/lidar_points_raw$
    - ^/<robot_namespace>/local_costmap/costmap$
    - ^/<robot_namespace>/map$
    - ^/<robot_namespace>/map_metadata$
    - ^/<robot_namespace>/microstrain/imu/data$
    - ^/<robot_namespace>/microstrain/imu/mag$
    - ^/<robot_namespace>/navsat$
    - ^/<robot_namespace>/obstacle_points$
    - ^/<robot_namespace>/odom$
    - ^/<robot_namespace>/odom_gt$
    - ^/<robot_namespace>/plan$
    - ^/<robot_namespace>/platform/safety_stop$
    - ^/<robot_namespace>/raw_points$
    - ^/<robot_namespace>/robot_description$
    - ^/<robot_namespace>/teleop_takeover$
    - ^/<robot_namespace>/tf$
    - ^/<robot_namespace>/tf_static$
    - ^/<robot_namespace>/trajectories$
    - ^/<robot_namespace>/waypoints_geo$
    best_effort_qos_topic_whitelist:
    - ^/<robot_namespace>/fixposition/odometry_enu$
    - ^/<robot_namespace>/fixposition/odometry_llh$
    - ^/<robot_namespace>/fixposition/odometry_smooth$
    - ^/<robot_namespace>/front_camera/image$
    - ^/<robot_namespace>/ground_points$
    - ^/<robot_namespace>/imu$
    - ^/<robot_namespace>/lidar_imu$
    - ^/<robot_namespace>/lidar_points_filtered$
    - ^/<robot_namespace>/lidar_points_raw$
    - ^/<robot_namespace>/microstrain/imu/data$
    - ^/<robot_namespace>/microstrain/imu/mag$
    - ^/<robot_namespace>/navsat$
    - ^/<robot_namespace>/obstacle_points$
    - ^/<robot_namespace>/raw_points$
    client_topic_whitelist:
    - ^/<robot_namespace>/clicked_point$
    - ^/<robot_namespace>/cmd_vel_teleop$
    - ^/<robot_namespace>/estop$
    - ^/<robot_namespace>/goal_pose$
    - ^/<robot_namespace>/initialpose$
    service_whitelist:
    - ^/<robot_namespace>/resume_autonomy$
    capabilities:
    - clientPublish
    - services
    - connectionGraph
    - assets
